### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by jjjan** [mitre-attack/bzar#10]
Hello i install bzar with zkg but how can i sure that loaded and work ?

**Comment by mfrndz** [comment]
Hello.  That's a good question.  I can direct you to some online resources, but unfortunately, I do not have pcaps or btests to share.  List of online resources below:

- **Wire Shark PCAP Repository**.  This website contains some useful PCAPS on SMB and DCE-RPC.  Does not provide full testing/coverage of everything BZAR detects, but it at least provides some partial coverage.  URL https://wiki.wireshark.org/SampleCaptures

- **Red Canary Atomic Testing**.  Red Canary provides very useful instructions on how execute specific ATT&CK Techniques, which can be very useful for testing BZAR and other security tools.  URL https://github.com/redcanaryco/atomic-red-team

- **MITRE CALDERA**. CALDERA™ is a cyber security framework designed to easily run autonomous breach-and-simulation exercises. It can also be used to run manual red-team engagements or automated incident response.  It is built on the MITRE ATT&CK™ framework and is an active research project at MITRE.  URL https://github.com/mitre/caldera

I hope this helps.

**Comment by jjjan** [comment]
thanks for replay i have this situation.
in diag of zeek i have:

==== No prof.log
==== No packet_filter.log
==== No loaded_scripts.log
====Zeek plugins: (none found)
does it bzar loaded? how can i sure about it?

check zkg list return this:
zeek/mitre-attack/bzar (installed: master) - BZAR - Bro/Zeek ATT&CK-based Analytics and Reporting.

i check smb with PsExec and run lots of pcap with this command  "bro -Cr example.pcap" and finally run atomic read team.

no notice log generate with mirte attack tag though! but i have lots of connection logs.

any idea.
