### ISSUE TITLE
Automated suppression with $identifier?

### ISSUE THREAD

**Issue by glwallum** [mitre-attack/bzar#5]
Hello,

I am working to suppress identical alerts, is there any built-in suppression in BZAR? Is there any way to hook the $identifier into the BZAR NOTICE?

**Comment by mfrndz** [comment]
I think so.  We could probably create a config option to set that variable. I'll look into it.

The next question will be, how much granularity do we want?  For example, suppress Discovery-related activity according to one value; suppress Execution-related activity according to a different value; and suppress Credential Access even differently?  Or just one config option to suppress them all?

**Comment by glwallum** [comment]
It would be great to have different suppression for each type of alert (discovery, execution, credential access) if possible.
