### ISSUE TITLE
PR to Zeek for the UUID/Endpoint Mapping

### ISSUE THREAD

**Issue by neu5ron** [mitre-attack/bzar#6]
First great work! This is awesome.
Have you all thought about creating a PR to Zeek for the UUID & Endpoint mappings you all have in this project?
```
The BZAR project adds 144 more Microsoft DCE-RPC Interface UUIDs (a.k.a. "endpoints") to the Bro/Zeek DCE_RPC::uuid_endpoint_map.

The BZAR project also adds 1,145 Microsoft DCE-RPC Interface Methods (a.k.a. "operations") to the Bro/Zeek DCE_RPC::operations.
```
reference:
https://github.com/mitre-attack/bzar#additional-dce-rpc-interfaces-and-methods

reference added things:
https://github.com/mitre-attack/bzar/blob/4be8432b43445b79e00e5a52144ed44486a4aefd/scripts/bzar_dce-rpc_consts.bro#L261
https://github.com/mitre-attack/bzar/blob/4be8432b43445b79e00e5a52144ed44486a4aefd/scripts/bzar_dce-rpc_consts.bro#L420

**Comment by ckreibich** [comment]
Totally agree here — Mark, those mappings are a terrific contribution, and the open-source project would love to adopt them if you're up for that.

**Comment by l0x-c0d3z** [comment]
I've taken the liberty of doing that PR.

https://github.com/zeek/zeek/issues/953

**Comment by l0x-c0d3z** [comment]
@mfrndz would it be okay for that code to be redistributed under the Zeek BSD license ?

**Comment by mfrndz** [comment]
Thank you very much for the feedback and the compliments.  We are looking into it.  I think it should be ok, just need to confirm with corporate.  Hope to respond soon.

**Comment by mfrndz** [comment]
@l0x-c0d3z I changed the license from Apache to BSD.  You should be good to go to redistribute under the Zeek BSD license.

**Comment by l0x-c0d3z** [comment]
Thanks a lot !

**Comment by l0x-c0d3z** [comment]
My PR over at Zeek has been merged: https://github.com/zeek/zeek/pull/954

I think we can close this. Thanks again.
