### ISSUE TITLE
Fix Zeek 3.1 Deprecations

### ISSUE THREAD

**Issue by bv3** [mitre-attack/bzar#7]
Any interest in a PR with Zeek 3.1 changes?  Rename .bro scripts to .zeek to eliminate deprecation warnings, switch to the new smb2_write_response event (thanks for the great comments to help with that), and switch from bro-pkg to zkg.  It's incompatible with Bro, of course.

**Comment by mfrndz** [comment]
Yes, that would be great.

**Comment by mfrndz** [comment]
Renamed .bro scripts to .zeek... complete.
